import { corFundoEscuro, corTextoClaro, corTextoMutado, corAzulPrincipal, corCard } from './Estilos'

export const EstilosPrincipal = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px 24px',
    backgroundColor: corFundoEscuro,
    color: corTextoClaro,
  },
  painel: {
    width: '100%',
    maxWidth: '920px',
    backgroundColor: corCard,
    borderRadius: 24,
    padding: '32px',
    boxSizing: 'border-box',
    boxShadow: '0 18px 48px rgba(0, 0, 0, 0.35)',
    display: 'flex',
    flexDirection: 'column',
    gap: '28px',
  },
  headerPanel: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '20px',
    borderBottom: '1px solid rgba(255,255,255,0.12)',
    paddingBottom: '18px',
  },
  headerInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    textAlign: 'left',
  },
  userName: {
    color: corTextoClaro,
    fontSize: '1.1rem',
    margin: 0,
    fontWeight: 600,
  },
  userTipo: {
    color: corTextoMutado,
    fontSize: '0.95rem',
    margin: 0,
  },
  link: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '10px 18px',
    borderRadius: '12px',
    backgroundColor: 'rgba(14, 75, 207, 0.15)',
    color: corAzulPrincipal,
    textDecoration: 'none',
    fontWeight: 700,
  },
  iconeLogo: {
    width: '140px',
    height: '140px',
    objectFit: 'contain',
    borderRadius: '24px',
    boxShadow: '0 16px 40px rgba(0, 0, 0, 0.35)',
    backgroundColor: '#0f172a',
    padding: '16px',
  },
  titulo: {
    fontSize: '2.4rem',
    fontWeight: 700,
    margin: 0,
    letterSpacing: '0.03em',
  },
  subtitulo: {
    fontSize: '1rem',
    color: corTextoMutado,
    margin: 0,
    maxWidth: '520px',
    lineHeight: 1.7,
  },
  saudacaoCard: {
    width: '100%',
    borderRadius: '18px',
    backgroundColor: 'rgba(255,255,255,0.04)',
    padding: '24px',
    boxSizing: 'border-box',
    textAlign: 'center',
  },
  saudacaoTitulo: {
    margin: 0,
    fontSize: '1.6rem',
    color: corTextoClaro,
    fontWeight: 700,
  },
  saudacaoTexto: {
    marginTop: '10px',
    fontSize: '1rem',
    color: corTextoMutado,
    lineHeight: 1.7,
  },
};

